/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R9SnapshotRouteImport } from './routes/9-snapshot'
import { Route as R8StateRouteImport } from './routes/8-state'
import { Route as R7EventRouteImport } from './routes/7-event'
import { Route as R6ListRouteImport } from './routes/6-list'
import { Route as R5ConditionalRouteImport } from './routes/5-conditional'
import { Route as R4ChildrenRouteImport } from './routes/4-children'
import { Route as R3PropsRouteImport } from './routes/3-props'
import { Route as R2ComponentsRouteImport } from './routes/2-components'
import { Route as R13EventEmissionRouteImport } from './routes/13-event-emission'
import { Route as R12TwoWayBindingRouteImport } from './routes/12-two-way-binding'
import { Route as R11ImmerRouteImport } from './routes/11-immer'
import { Route as R10ReferenceTypesRouteImport } from './routes/10-reference-types'
import { Route as R1JsxRouteImport } from './routes/1-jsx'
import { Route as IndexRouteImport } from './routes/index'

const R9SnapshotRoute = R9SnapshotRouteImport.update({
  id: '/9-snapshot',
  path: '/9-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const R8StateRoute = R8StateRouteImport.update({
  id: '/8-state',
  path: '/8-state',
  getParentRoute: () => rootRouteImport,
} as any)
const R7EventRoute = R7EventRouteImport.update({
  id: '/7-event',
  path: '/7-event',
  getParentRoute: () => rootRouteImport,
} as any)
const R6ListRoute = R6ListRouteImport.update({
  id: '/6-list',
  path: '/6-list',
  getParentRoute: () => rootRouteImport,
} as any)
const R5ConditionalRoute = R5ConditionalRouteImport.update({
  id: '/5-conditional',
  path: '/5-conditional',
  getParentRoute: () => rootRouteImport,
} as any)
const R4ChildrenRoute = R4ChildrenRouteImport.update({
  id: '/4-children',
  path: '/4-children',
  getParentRoute: () => rootRouteImport,
} as any)
const R3PropsRoute = R3PropsRouteImport.update({
  id: '/3-props',
  path: '/3-props',
  getParentRoute: () => rootRouteImport,
} as any)
const R2ComponentsRoute = R2ComponentsRouteImport.update({
  id: '/2-components',
  path: '/2-components',
  getParentRoute: () => rootRouteImport,
} as any)
const R13EventEmissionRoute = R13EventEmissionRouteImport.update({
  id: '/13-event-emission',
  path: '/13-event-emission',
  getParentRoute: () => rootRouteImport,
} as any)
const R12TwoWayBindingRoute = R12TwoWayBindingRouteImport.update({
  id: '/12-two-way-binding',
  path: '/12-two-way-binding',
  getParentRoute: () => rootRouteImport,
} as any)
const R11ImmerRoute = R11ImmerRouteImport.update({
  id: '/11-immer',
  path: '/11-immer',
  getParentRoute: () => rootRouteImport,
} as any)
const R10ReferenceTypesRoute = R10ReferenceTypesRouteImport.update({
  id: '/10-reference-types',
  path: '/10-reference-types',
  getParentRoute: () => rootRouteImport,
} as any)
const R1JsxRoute = R1JsxRouteImport.update({
  id: '/1-jsx',
  path: '/1-jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
  '/10-reference-types': typeof R10ReferenceTypesRoute
  '/11-immer': typeof R11ImmerRoute
  '/12-two-way-binding': typeof R12TwoWayBindingRoute
  '/13-event-emission': typeof R13EventEmissionRoute
  '/2-components': typeof R2ComponentsRoute
  '/3-props': typeof R3PropsRoute
  '/4-children': typeof R4ChildrenRoute
  '/5-conditional': typeof R5ConditionalRoute
  '/6-list': typeof R6ListRoute
  '/7-event': typeof R7EventRoute
  '/8-state': typeof R8StateRoute
  '/9-snapshot': typeof R9SnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
  '/10-reference-types': typeof R10ReferenceTypesRoute
  '/11-immer': typeof R11ImmerRoute
  '/12-two-way-binding': typeof R12TwoWayBindingRoute
  '/13-event-emission': typeof R13EventEmissionRoute
  '/2-components': typeof R2ComponentsRoute
  '/3-props': typeof R3PropsRoute
  '/4-children': typeof R4ChildrenRoute
  '/5-conditional': typeof R5ConditionalRoute
  '/6-list': typeof R6ListRoute
  '/7-event': typeof R7EventRoute
  '/8-state': typeof R8StateRoute
  '/9-snapshot': typeof R9SnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
  '/10-reference-types': typeof R10ReferenceTypesRoute
  '/11-immer': typeof R11ImmerRoute
  '/12-two-way-binding': typeof R12TwoWayBindingRoute
  '/13-event-emission': typeof R13EventEmissionRoute
  '/2-components': typeof R2ComponentsRoute
  '/3-props': typeof R3PropsRoute
  '/4-children': typeof R4ChildrenRoute
  '/5-conditional': typeof R5ConditionalRoute
  '/6-list': typeof R6ListRoute
  '/7-event': typeof R7EventRoute
  '/8-state': typeof R8StateRoute
  '/9-snapshot': typeof R9SnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1-jsx'
    | '/10-reference-types'
    | '/11-immer'
    | '/12-two-way-binding'
    | '/13-event-emission'
    | '/2-components'
    | '/3-props'
    | '/4-children'
    | '/5-conditional'
    | '/6-list'
    | '/7-event'
    | '/8-state'
    | '/9-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1-jsx'
    | '/10-reference-types'
    | '/11-immer'
    | '/12-two-way-binding'
    | '/13-event-emission'
    | '/2-components'
    | '/3-props'
    | '/4-children'
    | '/5-conditional'
    | '/6-list'
    | '/7-event'
    | '/8-state'
    | '/9-snapshot'
  id:
    | '__root__'
    | '/'
    | '/1-jsx'
    | '/10-reference-types'
    | '/11-immer'
    | '/12-two-way-binding'
    | '/13-event-emission'
    | '/2-components'
    | '/3-props'
    | '/4-children'
    | '/5-conditional'
    | '/6-list'
    | '/7-event'
    | '/8-state'
    | '/9-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1JsxRoute: typeof R1JsxRoute
  R10ReferenceTypesRoute: typeof R10ReferenceTypesRoute
  R11ImmerRoute: typeof R11ImmerRoute
  R12TwoWayBindingRoute: typeof R12TwoWayBindingRoute
  R13EventEmissionRoute: typeof R13EventEmissionRoute
  R2ComponentsRoute: typeof R2ComponentsRoute
  R3PropsRoute: typeof R3PropsRoute
  R4ChildrenRoute: typeof R4ChildrenRoute
  R5ConditionalRoute: typeof R5ConditionalRoute
  R6ListRoute: typeof R6ListRoute
  R7EventRoute: typeof R7EventRoute
  R8StateRoute: typeof R8StateRoute
  R9SnapshotRoute: typeof R9SnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/9-snapshot': {
      id: '/9-snapshot'
      path: '/9-snapshot'
      fullPath: '/9-snapshot'
      preLoaderRoute: typeof R9SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8-state': {
      id: '/8-state'
      path: '/8-state'
      fullPath: '/8-state'
      preLoaderRoute: typeof R8StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7-event': {
      id: '/7-event'
      path: '/7-event'
      fullPath: '/7-event'
      preLoaderRoute: typeof R7EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/6-list': {
      id: '/6-list'
      path: '/6-list'
      fullPath: '/6-list'
      preLoaderRoute: typeof R6ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5-conditional': {
      id: '/5-conditional'
      path: '/5-conditional'
      fullPath: '/5-conditional'
      preLoaderRoute: typeof R5ConditionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4-children': {
      id: '/4-children'
      path: '/4-children'
      fullPath: '/4-children'
      preLoaderRoute: typeof R4ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3-props': {
      id: '/3-props'
      path: '/3-props'
      fullPath: '/3-props'
      preLoaderRoute: typeof R3PropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2-components': {
      id: '/2-components'
      path: '/2-components'
      fullPath: '/2-components'
      preLoaderRoute: typeof R2ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13-event-emission': {
      id: '/13-event-emission'
      path: '/13-event-emission'
      fullPath: '/13-event-emission'
      preLoaderRoute: typeof R13EventEmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12-two-way-binding': {
      id: '/12-two-way-binding'
      path: '/12-two-way-binding'
      fullPath: '/12-two-way-binding'
      preLoaderRoute: typeof R12TwoWayBindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/11-immer': {
      id: '/11-immer'
      path: '/11-immer'
      fullPath: '/11-immer'
      preLoaderRoute: typeof R11ImmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10-reference-types': {
      id: '/10-reference-types'
      path: '/10-reference-types'
      fullPath: '/10-reference-types'
      preLoaderRoute: typeof R10ReferenceTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1-jsx': {
      id: '/1-jsx'
      path: '/1-jsx'
      fullPath: '/1-jsx'
      preLoaderRoute: typeof R1JsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1JsxRoute: R1JsxRoute,
  R10ReferenceTypesRoute: R10ReferenceTypesRoute,
  R11ImmerRoute: R11ImmerRoute,
  R12TwoWayBindingRoute: R12TwoWayBindingRoute,
  R13EventEmissionRoute: R13EventEmissionRoute,
  R2ComponentsRoute: R2ComponentsRoute,
  R3PropsRoute: R3PropsRoute,
  R4ChildrenRoute: R4ChildrenRoute,
  R5ConditionalRoute: R5ConditionalRoute,
  R6ListRoute: R6ListRoute,
  R7EventRoute: R7EventRoute,
  R8StateRoute: R8StateRoute,
  R9SnapshotRoute: R9SnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
