/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R1JsxRouteImport } from './routes/1-jsx'
import { Route as IndexRouteImport } from './routes/index'

const R1JsxRoute = R1JsxRouteImport.update({
  id: '/1-jsx',
  path: '/1-jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1-jsx': typeof R1JsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/1-jsx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/1-jsx'
  id: '__root__' | '/' | '/1-jsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1JsxRoute: typeof R1JsxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/1-jsx': {
      id: '/1-jsx'
      path: '/1-jsx'
      fullPath: '/1-jsx'
      preLoaderRoute: typeof R1JsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1JsxRoute: R1JsxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
